service: sport-monks-fixture-processor
provider:
  name: aws
  runtime: nodejs12.x
stage: dev
region: eu-west-1
memorySize: 128
timeout: 30
# you can define service wide environment variables here
#  environment:
#    variable1: value1
functions:
  fixtures:
    handler: handler.processFixtures
     - schedule: cron(0 3 * * *)
#    Define function environment variables here
#    environment:
#      variable2: value2
plugins:
  - serverless-offline